version: "3"

services:
  no-youre-a-docker:
    build: .
    image: seaside
    container_name: landlocked
    volumes:
    - "./yesmate:/root/inhere"
    working_dir: /root/inhere
    command: python -m SimpleHTTPServer 1998
    ports:
      - 8080:1998

  back-end-poc:
    build: server
    image: lighthouse
    container_name: windermere
    volumes:
    - "./server:/api"
    working_dir: /api
    command: node app.js
    ports:
      - 8085:1886

